/**
 * build-tokens.mjs
 * Generates tokens/build/tokens.css from the token layers — the SINGLE source of truth.
 * Resolves component -> semantic -> primitive ref chains and emits CSS custom properties
 * under the --prodigeui-* namespace. Run this whenever token JSON changes.
 *
 * Usage: node scripts/build-tokens.mjs   (add --check to fail if the file is stale)
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const BASE = resolve(__dirname, '../prodigeui');
const tokensDir = join(BASE, 'tokens');
const OUT = join(tokensDir, 'build', 'tokens.css');

const primitive = JSON.parse(readFileSync(join(tokensDir, 'primitive.tokens.json'), 'utf-8')).tokens;
const semantic = JSON.parse(readFileSync(join(tokensDir, 'semantic.tokens.json'), 'utf-8')).tokens;
const component = JSON.parse(readFileSync(join(tokensDir, 'component.tokens.json'), 'utf-8')).tokens;

const ALL = { ...primitive, ...semantic, ...component };

function formatValue(v) {
  if (typeof v === 'string') return v;
  if (v && typeof v === 'object') {
    // shadow object: { x, y, blur, spread, color }  (x may include "inset")
    if (v.color !== undefined) return `${v.x} ${v.y} ${v.blur} ${v.spread} ${v.color}`.trim();
  }
  return String(v);
}

function resolveValue(key, seen = new Set()) {
  if (seen.has(key)) return null;
  seen.add(key);
  const t = ALL[key];
  if (!t) return null;
  if (t.value !== undefined) return formatValue(t.value);
  if (t.ref) return resolveValue(t.ref, seen);
  return null;
}

// Semantic key -> CSS custom property name (matches established convention)
function semanticVarName(key) {
  if (key.startsWith('typography.font-family.')) return 'font-family-' + key.split('.').slice(2).join('-');
  if (key.startsWith('typography.size.')) return 'font-size-' + key.split('.').slice(2).join('-');
  if (key.startsWith('typography.weight.')) return 'font-weight-' + key.split('.').slice(2).join('-');
  if (key.startsWith('typography.leading.')) return 'line-height-' + key.split('.').slice(2).join('-');
  return key.replace(/\./g, '-');
}

function cssVar(name, value) {
  return `  --prodigeui-${name}: ${value};`;
}

// --- Build sections ---
const lines = [];
lines.push('/* ProdigeUI Design Tokens — CSS Custom Properties');
lines.push(' * GENERATED by scripts/build-tokens.mjs from the token layers (primitive -> semantic -> component).');
lines.push(' * Do not edit by hand. Run `node scripts/build-tokens.mjs` after changing token JSON.');
lines.push(' * Use these variables in all visual styling. Never use raw values directly.');
lines.push(' */');
lines.push('');
lines.push(':root {');

function section(title, entries) {
  if (!entries.length) return;
  lines.push(`  /* === ${title} === */`);
  lines.push(...entries);
  lines.push('');
}

// Semantic, bucketed by role
const semColor = [], semType = [], semSpace = [], semRadius = [], semShadow = [], semBorder = [], semZ = [], semMotion = [], semOpacity = [];
for (const key of Object.keys(semantic)) {
  const val = resolveValue(key);
  if (val == null) continue;
  const line = cssVar(semanticVarName(key), val);
  if (key.startsWith('color.')) semColor.push(line);
  else if (key.startsWith('typography.')) semType.push(line);
  else if (key.startsWith('space.') || key.startsWith('container.')) semSpace.push(line);
  else if (key.startsWith('radius.')) semRadius.push(line);
  else if (key.startsWith('shadow.')) semShadow.push(line);
  else if (key.startsWith('border.')) semBorder.push(line);
  else if (key.startsWith('z.')) semZ.push(line);
  else if (key.startsWith('motion.')) semMotion.push(line);
  else if (key.startsWith('opacity.')) semOpacity.push(line);
}

// Component tokens, bucketed by resolved type
const compByType = { color: [], typography: [], spacing: [], radius: [], shadow: [], border: [], 'z-index': [], motion: [] };
for (const [key, t] of Object.entries(component)) {
  const val = resolveValue(key);
  if (val == null) continue;
  const line = cssVar(key.replace(/\./g, '-'), val);
  (compByType[t.type] || (compByType[t.type] = [])).push(line);
}

section('Color: Semantic Roles', semColor);
section('Typography: Semantic', semType);
section('Spacing & Containers: Semantic', semSpace);
section('Radius: Semantic', semRadius);
section('Shadow: Semantic', semShadow);
section('Border: Semantic', semBorder);
section('Z-Index: Semantic', semZ);
section('Motion: Semantic', semMotion);
section('Opacity: Semantic', semOpacity);

section('Component: Color', compByType.color);
section('Component: Typography', compByType.typography);
section('Component: Spacing', compByType.spacing);
section('Component: Radius', compByType.radius);
section('Component: Shadow', compByType.shadow);
section('Component: Border', compByType.border);
section('Component: Z-Index', compByType['z-index']);
section('Component: Motion', compByType.motion);

// Primitive extras intentionally exposed (accent family + expressive radius + glow discipline)
const extras = [];
for (const k of ['palette.ignite.s400', 'palette.ignite.s500', 'palette.ignite.s600']) {
  if (primitive[k]) extras.push(cssVar('color-ignite-' + k.split('.').pop().replace('s', ''), primitive[k].value));
}
for (const k of ['scale.radius.x2l', 'scale.radius.x3l', 'scale.radius.x4l']) {
  if (primitive[k]) extras.push(cssVar('radius-' + k.split('.').pop(), primitive[k].value));
}
for (const [k, name] of [['effect.glow.ambient-min', 'glow-ambient-min'], ['effect.glow.ambient-max', 'glow-ambient-max'], ['effect.glow.bloom-peak', 'glow-bloom-peak']]) {
  if (primitive[k]) extras.push(cssVar(name, primitive[k].value));
}
section('Primitive extras (2026 accent family, expressive radius, dark-hero glow discipline)', extras);

// trim trailing blank line inside root
while (lines[lines.length - 1] === '') lines.pop();
lines.push('}');
lines.push('');

const css = lines.join('\n');

if (process.argv.includes('--check')) {
  const current = (() => { try { return readFileSync(OUT, 'utf-8'); } catch { return ''; } })();
  if (current.trim() !== css.trim()) {
    console.error('tokens.css is STALE. Run: node scripts/build-tokens.mjs');
    process.exit(1);
  }
  console.log('tokens.css is up to date.');
  process.exit(0);
}

writeFileSync(OUT, css);
console.log(`Generated ${OUT} (${Object.keys(semantic).length} semantic + ${Object.keys(component).length} component tokens).`);
